const data = {
  products: [
    {
      _id: '1',
      name: 'One Plus 8T',
      slug: 'one-plus-8t',
      category: 'Phone',
      image: '/images/p1.jpg',
      price: 50000,
      countInStock: 10,
      brand: 'One Plus',
      rating: 5.0,
      numReviews: 10,
      description: 'Used for 1 year',
    },
    {
      _id: '2',
      name: 'iPhone se',
      slug: 'iphone-se',
      category: 'Phone',
      image: '/images/p2.jpg',
      price: 40000,
      countInStock: 0,
      brand: 'Iphone',
      rating: 4.0,
      numReviews: 10,
      description: 'Used for 1 year',
    },
    {
      _id: '3',
      name: 'Asus Monitor',
      slug: 'asus-monitor',
      category: 'Monitor',
      image: '/images/p3.jpg',
      price: 30000,
      countInStock: 6,
      brand: 'Asus',
      rating: 4.5,
      numReviews: 10,
      description: 'Used for 1 year',
    },
    {
      _id: '4',
      name: 'Asus Laptop',
      slug: 'asus-laptop',
      category: 'Laptop',
      image: '/images/p4.jpg',
      price: 80000,
      countInStock: 1,
      brand: 'Asus',
      rating: 4.5,
      numReviews: 10,
      description: 'Used for 1 year',
    },
  ],
};
export default data;
