const data = {
  products: [
    {
      name: 'One Plus 8T',
      slug: 'one-plus-8t',
      category: 'Phone',
      image: '/images/p1.jpg',
      price: '50000 TAKA',
      countInStock: 10,
      brand: 'One Plus',
      rating: 5.0,
      numReviews: 10,
      description: 'Used for 1 year',
    },
    {
      name: 'iPhone se',
      slug: 'iphone-se',
      category: 'Phone',
      image: '/images/p2.jpg',
      price: '40000 TAKA',
      countInStock: 0,
      brand: 'Iphone',
      rating: 4.0,
      numReviews: 10,
      description: 'Used for 1 year',
    },
    {
      name: 'Asus Monitor',
      slug: 'asus-monitor',
      category: 'Monitor',
      image: '/images/p3.jpg',
      price: '30000 TAKA',
      countInStock: 6,
      brand: 'Asus',
      rating: 4.5,
      numReviews: 10,
      description: 'Used for 1 year',
    },
    {
      name: 'Asus Laptop',
      slug: 'asus-laptop',
      category: 'Laptop',
      image: '/images/p4.jpg',
      price: '80000 TAKA',
      countInStock: 1,
      brand: 'Asus',
      rating: 4.5,
      numReviews: 10,
      description: 'Used for 1 year',
    },
  ],
};
export default data;
