const data = {
  products: [
    {
      name: 'One Plus 8T',
      slug: 'one-plus-8t',
      category: 'Phone',
      image: '/image/p1.jpg',
      price: 50000,
      inStock: 5,
      brand: 'One Plus',
      rating: 5.0,
      numReviews: 10,
      description: 'Used for 1 year',
    },
    {
      name: 'Iphone se',
      slug: 'iphone-se',
      category: 'Phone',
      image: '/image/p2.jpg',
      price: 40000,
      inStock: 2,
      brand: 'Iphone',
      rating: 4.0,
      numReviews: 10,
      description: 'Used for 1 year',
    },
    {
      name: 'Asus Monitor',
      slug: 'asus-monitor',
      category: 'Monitor',
      image: '/image/p3.jpg',
      price: 30000,
      inStock: 6,
      brand: 'Asus',
      rating: 4.5,
      numReviews: 10,
      description: 'Used for 1 year',
    },
    {
      name: 'Asus Laptop',
      slug: 'asus-laptop',
      category: 'Laptop',
      image: '/image/p4.jpg',
      price: 80000,
      inStock: 1,
      brand: 'Asus',
      rating: 4.5,
      numReviews: 10,
      description: 'Used for 1 year',
    },
  ],
};
export default data;
